#region Fog Weather Struct Definition

/// @param {Real} index		Unique value generated by GML during compilation that represents this struct asset.
function str_fog(_index) : str_base(_index) constructor {
	flags			= STR_FLAG_PERSISTENT;
	
	// 
	curLayers		= ds_list_create();
	uPlayerPos		= shader_get_uniform(shd_fog_holepunch, "playerPos");
	
	/// @description 
	///	The fog weather struct's destroy event. It will clean up anything that isn't automatically cleaned up 
	/// by GameMaker when this struct is destroyed/out of scope.
	///	
	destroy_event = function(){
		var _length = ds_list_size(curLayers);
		for (var i = 0; i < _length; i++)
			delete curLayers[| i];
		ds_list_destroy(curLayers);
	}
	
	/// @description 
	///	Render all active fog layers onto the application surface. On top of that, their positions will be
	/// updated according to the speeds each respective layer is set to move at, and their opacity.
	/// 
	draw_end_event = function(){
		// 
		var _curLayers	= curLayers;
		var _length		= ds_list_size(_curLayers);
		if (_length == 0) // Exit without processing anything if there are currently no layers of fog active.
			return;
		
		// 
		var _sprWidth	= sprite_get_width(spr_fog);
		var _sprHeight	= sprite_get_height(spr_fog);
		var _delta		= global.deltaTime;
		var _uPlayerPos	= uPlayerPos;
		
		// 
		shader_set(shd_fog_holepunch);
		with(PLAYER) { shader_set_uniform_f(_uPlayerPos, x, y - 12); }
		
		// 
		for (var i = 0; i < _length; i++){
			with(curLayers[| i]){
				// 
				if (targetAlpha == 0.0){
					alpha -= _delta * 0.01;
					if (alpha <= 0.0){
						ds_list_delete(_curLayers, i);
						_length--;
						i--;
						continue;
					}
				} else{
					alpha += _delta * 0.01;
					if (alpha > targetAlpha)
						alpha = targetAlpha;
				}
					
				// 
				x += xSpeed * _delta;
				if (abs(x) >= _sprWidth * scale)
					x -= _sprWidth * scale * sign(xSpeed);
				
				// 
				y += ySpeed * _delta;
				if (abs(y) >= _sprHeight * scale)
					y -= _sprHeight * scale * sign(ySpeed);
					
				// 
				draw_sprite_tiled_ext(spr_fog, 0, x, y, scale, scale, COLOR_TRUE_WHITE, alpha);
			}
		}
		shader_reset();
	}
	
	/// @description 
	///	
	/// 
	///	@param {Real}	xSpeed	How fast and what direction (- left, + right) the layer will move along the x axis.
	/// @param {Real}	ySpeed	How fast and what direction (- up, + down) the layer will move along the y axis.
	/// @param {Real}	alpha	Overall opacity of the layer in question.
	/// @param {Real}	scale	(Optional) Scaling of the fog layer.
	add_layer = function(_xSpeed, _ySpeed, _alpha, _scale = 1.0){
		ds_list_add(curLayers, {
			x			: 0.0,
			y			: 0.0,
			alpha		: 0.0,
			xSpeed		: _xSpeed,
			ySpeed		: _ySpeed,
			targetAlpha	: _alpha,
			scale		: _scale
		});
	}
	
	/// @description 
	///	
	/// 
	///	@param {Real}	index
	remove_layer = function(_index){
		
	}
}

#endregion Fog Weather Struct Definition